### ISSUE TITLE
端口握手不成功

### ISSUE THREAD

**Issue by deku772** [sms-wyt/stcflash#1]
deepin 20
普中c51单片机 已在windows测试过单片机烧录没问题
python环境已配置，端口握手不成功，不知道是不是波特率的问题。
烦请解答一二，感激不尽

切换至最高波特率: 

Traceback (most recent call last):
  File "/home/mysa/tool/stcflash/stcflash.py", line 1412, in <module>
    main()
  File "/home/mysa/tool/stcflash/stcflash.py", line 1408, in main
    program(Programmer(conn, opts.protocol), code, opts.erase_eeprom)
  File "/home/mysa/tool/stcflash/stcflash.py", line 992, in program
    prog.handshake() 
  File "/home/mysa/tool/stcflash/stcflash.py", line 818, in handshake
    raise IOError()
IOError
make: *** [makefile:19：flash] 错误 1

**Comment by sms-wyt** [comment]
请问你是在Windows平台还是linux平台测试的？你的单片机是STC89系列的，如果在Windows平台，可能会出现握手失败的情况。试试指定协议下载，比如python stcflash.py --protocol 89 program.hex

**Comment by deku772** [comment]
是在linux测试的。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;sms-wyt&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月28日(星期一) 凌晨0:51
收件人:&nbsp;&quot;sms-wyt/stcflash&quot;<stcflash@noreply.github.com&gt;;
抄送:&nbsp;&quot;Deku&quot;<13594611244@163.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sms-wyt/stcflash] 端口握手不成功 (#1)

**Comment by deku772** [comment]
linux也指定协议了参数和比特率都添加了，并没有握手成功，但是stcflash已经检测出单片机类型和参数------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;sms-wyt&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月28日(星期一) 凌晨0:51
收件人:&nbsp;&quot;sms-wyt/stcflash&quot;<stcflash@noreply.github.com&gt;;
抄送:&nbsp;&quot;Deku&quot;<13594611244@163.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sms-wyt/stcflash] 端口握手不成功 (#1)

**Comment by sms-wyt** [comment]
你的单片机是什么型号的？如果不是较新的STC8系列和STC15系列，那就不支持波特率指定。这条试过了吗？python stcflash.py --protocol 89 program.hex或者Python stcflash.py program.hex

**Comment by deku772** [comment]
stc89c516------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;sms-wyt&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月28日(星期一) 上午7:20
收件人:&nbsp;&quot;sms-wyt/stcflash&quot;<stcflash@noreply.github.com&gt;;
抄送:&nbsp;&quot;Deku&quot;<13594611244@163.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sms-wyt/stcflash] 端口握手不成功 (#1)

**Comment by sms-wyt** [comment]
我之前在linux平台试过STC89C52可以正常烧录，STC89C51应该也可以烧录。你试过在Windows平台用stcflash可以烧录吧？另外，你可以访问https://github.com/laborer/stcflash，这个是原作者的文件，你git clone下来，看看能不能烧录。你也可以加我的QQ 936308890一起讨论。
