### ISSUE TITLE
STC8H08擦除芯片时超时报错

### ISSUE THREAD

**Issue by ninewang** [sms-wyt/stcflash#4]
开始擦除芯片...Traceback (most recent call last):
  File "/USR/work/waterrules/software/STC8H_sdcc/stcflash.py", line 1413, in <module>
    main()
  File "/USR/work/waterrules/software/STC8H_sdcc/stcflash.py", line 1409, in main
    program(Programmer(conn, opts.protocol), code, opts.erase_eeprom)
  File "/USR/work/waterrules/software/STC8H_sdcc/stcflash.py", line 1004, in program
    prog.erase() 
  File "/USR/work/waterrules/software/STC8H_sdcc/stcflash.py", line 839, in erase
    cmd, dat = self.recv(10)
  File "/USR/work/waterrules/software/STC8H_sdcc/stcflash.py", line 425, in recv
    raise IOError()
OSError

**Comment by yunline** [comment]
STC8G1K08也不行
```
通信端口：COM5  最低波特率：2400 bps
检测目标...完成
系统时钟频率: 23.880MHz        
掉电唤醒定时器频率: 35.775KHz  
内部参考电压: 1191 mV
低压检测电压: 2.2 V
内部安排测试时间: 2022年6月29日
单片机型号: STC8G1K08-8PIN     
固件版本号: 7.3.12U
程序空间: 8KB
切换至最高波特率: 115200 bps
开始擦除芯片...Traceback (most recent call last):
  File "X:\stc51\stcflash-master\stcflash.py", line 1412, in <module>
    main()
  File "X:\stc51\stcflash-master\stcflash.py", line 1408, in main    
    program(Programmer(conn, opts.protocol), code, opts.erase_eeprom)
  File "X:\stc51\stcflash-master\stcflash.py", line 1003, in program 
    prog.erase()
  File "X:\stc51\stcflash-master\stcflash.py", line 838, in erase
    cmd, dat = self.recv(10)
  File "X:\stc51\stcflash-master\stcflash.py", line 425, in recv
    raise IOError()
OSError
```

**Comment by sms-wyt** [comment]
手头没有这两款单片机测试，你可以根据报错的地方修改源码，看看能不能正常工作？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月12日(周六) 下午4:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [sms-wyt/stcflash] STC8H08擦除芯片时超时报错 (Issue #4)




 
STC8G1K08也不行
 通信端口：COM5  最低波特率：2400 bps 检测目标...完成 系统时钟频率: 23.880MHz         掉电唤醒定时器频率: 35.775KHz   内部参考电压: 1191 mV 低压检测电压: 2.2 V 内部安排测试时间: 2022年6月29日 单片机型号: STC8G1K08-8PIN      固件版本号: 7.3.12U 程序空间: 8KB 切换至最高波特率: 115200 bps 开始擦除芯片...Traceback (most recent call last):   File "X:\stc51\stcflash-master\stcflash.py", line 1412, in <module&gt;     main()   File "X:\stc51\stcflash-master\stcflash.py", line 1408, in main         program(Programmer(conn, opts.protocol), code, opts.erase_eeprom)   File "X:\stc51\stcflash-master\stcflash.py", line 1003, in program      prog.erase()   File "X:\stc51\stcflash-master\stcflash.py", line 838, in erase     cmd, dat = self.recv(10)   File "X:\stc51\stcflash-master\stcflash.py", line 425, in recv     raise IOError() OSError

**Comment by vlate** [comment]
STC芯片需用专用工具：

项目配置里烧录工具选stcgal
pip安装stcgal : pip install stagal
